Fix ci fail
Czaki/sphinx-qt-documentation pull request #3
Opened 2020-02-10 21:31 UTC by renefritze

I've identified the issue that previously failed the CI. However this needs a custom or modified docker image for Azure, which I'll get to push tomorrow.

2020-02-10 21:49 UTC, Czaki requested changes
Why did you use docker image job instead of UsePythonVersion task? (I`m not an expert in azure pipelines)

2020-02-10 21:49 UTC, Czaki commented on setup.cfg
> -python_requires='>=3'
Pleas see current version from repository. The problem here are `'`. Without theme everything work fine.

2020-02-10 21:49 UTC, Czaki commented on setup.py
> +    install_requires=['sphinx', 'docutils'],
also this is in setup.cfg.

2020-02-11 09:06 UTC, renefritze commented
> Why did you use docker image job instead of UsePythonVersion task? (I`m not an expert in azure pipelines)

Generally I don't like to use the CI Provider's own language ecosystem. Using containers to run your CI in makes it a lot easier to switch Providers, plus I don't need to learn how to manage python (or , c++, etc.) versions in different providers.

2020-02-11 10:45 UTC, Czaki commented
> Generally I don't like to use the CI Provider's own language ecosystem. Using containers to run your CI in makes it a lot easier to switch Providers, plus I don't need to learn how to manage python (or , c++, etc.) versions in different providers.

I see. But this create problems with testing application with GUI components. Did you have some script which allow to run GUI test under docker? 

Maybe you need to setup xvfb.

2020-02-11 10:53 UTC, renefritze commented
Yes, xvfb works nicely for running anything that needs X from inside the container.

2020-02-11 10:55 UTC, renefritze commented
Sorry for the commit spam btw, but the quoting/arg thing in azure is driving me nuts.

2020-02-11 10:56 UTC, Czaki commented
No problem.I can squash this PR to single commit.

2020-02-11 11:27 UTC, renefritze commented
Could you please update the version on pypi after merging?

2020-02-11 11:31 UTC, Czaki approved these changes

2020-02-11 11:32 UTC, merged

2020-02-11 11:52 UTC, Czaki commented
@renefritze uploaded.